name: Convert JSON to to SCSS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Install json-sass (or another CLI tool that converts JSON to SCSS)
      - name: Install json-sass
        run: npm install -g json-sass

      # Convert the JSON tokens to SCSS
      - name: Convert JSON to SCSS
        run: |
          json-sass ./tokens.json > ./tokens.scss

      # Commit and push the SCSS changes back to the repository
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add ./tokens.scss
          git commit -m 'Auto-generated SCSS from JSON tokens'
          git push https://x-access-token:${{ secrets.WORK_FLOW }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
