name: Release Branch & PR

on:
  push:
    branches: [dev]
    paths:
      - 'CHANGELOG.md'

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  publish:
    name: 'Create Release Branch & PR'
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Library
        run: npm run build

      - name: Build Storybook
        run: npm run build-storybook

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Storybook Tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server storybook-static --port 6006 --silent" \
          "npx wait-on tcp:127.0.0.1:6006 && npm run test-storybook"

      - name: Get Version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Release Branch
        run: |
          git checkout -b release/${{ env.VERSION }}
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git push origin release/${{ env.VERSION }}

      - name: Create Pull Request
        run: |
          gh pr create \
            -B staging \
            -H release/${{ env.VERSION }} \
            --title "New Release: ${{ env.VERSION }}" \
            --body "Changes include updates for the new version release. Please review the changes carefully before merging."
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_GIT_TOKEN }}
