name: Package Release

on:
  push:
    branches: [staging]
    paths:
      - 'CHANGELOG.md'

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@your-org' # Replace with your organization or scope

      - name: Install dependencies
        run: npm install # Use 'npm install' if you don't use npm

      - name: Build Angular Library
        run: npm run build # Replace 'build:lib' with your specific build command for the library

      - name: Build Storybook
        run: npm run build-storybook # Replace 'npm' with 'npm' if needed

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Storybook Tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server storybook-static --port 6006 --silent" \
          "npx wait-on tcp:127.0.0.1:6006 && npm test-storybook"

      - name: Publish Package
        run: npm publish # Use 'npm publish' if you use npm
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_GIT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.REPO_GIT_TOKEN }}
